# This is a basic workflow to help you get started with Actions

name: Test Kitchen

on: [ push, workflow_dispatch ]
  
jobs:
  Kitchen-Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Check if Chef installed
        continue-on-error: true
        id: check
        run: sudo dpkg -l | grep chef
        
      - name: Install ChefWorkstation v21.2.278
        if: steps.check.outcome == 'failure'
        run: |
          wget -q https://packages.chef.io/files/stable/chef-workstation/21.2.278/ubuntu/20.04/chef-workstation_21.2.278-1_amd64.deb
          sudo dpkg -i chef-workstation_21.2.278-1_amd64.deb
          chef -v
  
      - name: Install Docker
        run: |
          sudo apt update -y
          sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
          sudo apt install -y docker-compose
          docker -v
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          sudo service docker start
          service docker status

      - name: Converge
        run: |
          kitchen destroy
          kitchen create
          kitchen converge
          
      - name: Run Test
        run: kitchen verify
        
      - name: Cleanup Containers 
        if: always()
        run: kitchen destroy
        
